name: CI/CD Pipeline

on:  
  push:    
    branches:      
      - main

jobs:  
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.organization=your_organization_key 

  build-deploy:    
    runs-on: ubuntu-latest    
    steps:      
      - name: Checkout code        
        uses: actions/checkout@v4        
        with:          
          fetch-depth: 0      

      - name: Install Minikube        
        run: |          
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64          
          chmod +x minikube          
          sudo mv minikube /usr/local/bin/      

      - name: Install kubectl        
        run: |          
          curl -LO "https://dl.k8s.io/release/v1.26.3/bin/linux/amd64/kubectl"          
          chmod +x kubectl          
          sudo mv kubectl /usr/local/bin/      

      - name: Setting up Docker         
        uses: docker/setup-buildx-action@v3      

      - name: Start Minikube        
        run: |          
          minikube start --driver=docker      

      - name: Set up Node.js        
        uses: actions/setup-node@v4        
        with:          
          node-version: 20   

      - name: Downloading Package        
        run: npm init -y      

      - name: Logging into Docker Hub        
        uses: docker/login-action@v3        
        with:          
          username: ${{ secrets.DOCKER_USERNAME }}          
          password: ${{ secrets.DOCKER_PASSWORD }}      

      - name: Build Docker image
        run: |
          docker build -t docker.io/zaza02/myapp:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push docker.io/zaza02/myapp:latest   

      - name: Pushing Docker Image        
        run: docker push docker.io/zaza02/myapp:latest         

      - name: Deploy to Kubernetes         
        run: |          
          kubectl apply -f deployment.yaml                 
